language: ruby
sudo: required
services:
  - docker
before_script:
  - gem build gorgon.gemspec
  - gem install gorgon
  - pushd tests/end_to_end
  - bundle install
  - docker-compose up -d
  - sleep 15
  - bundle exec gorgon listen &
  - bundle exec gorgon || true # ignore error status from gorgon run
  - popd
script: "bundle exec rspec spec"
