language: ruby
sudo: required
services:
  - docker
before_script:
  - gem build gorgon.gemspec
  - gem install gorgon
  - pushd tests/end_to_end
  - bundle install
  - mkdir -p ~/.ssh
  - ssh-keygen -f ~/.ssh/id_rsa -t rsa -N ''
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys
  - docker-compose up -d
  - sleep 15
  - bundle exec gorgon listen &
  - bundle exec gorgon || true # ignore error status from gorgon run
  - popd
script: "bundle exec rspec spec"
