sudo: required
services:
  - docker
before_script:
  - ./run_dev_environment.sh &
  - sleep 15
  - ./run_listener.sh &
  - ./run_gorgon.sh || true # ignore error status from gorgon run
script: docker-compose exec originator rake
