language: ruby
sudo: required
services:
  - rabbitmq
before_script:
  - pushd tests/end_to_end
  - bundle install
  - bundle exec gorgon listen &
  - sleep 5
  - popd
script: "bundle exec rspec spec"
