language: ruby
sudo: required
services:
  - docker
before_script:
  - docker-compose build
  - docker-compose up -d
  - sleep 15
  - docker-compose exec listener /bin/bash -c 'cd tests/end_to_end && gorgon listen' &
  - docker-compose exec listener /bin/bash -c 'cd tests/end_to_end && gorgon' || true # ignore error status from gorgon run
script: "docker-compose exec listener rspec"
